---
title: '[GitHub Actions]プルリクで動かすCIをon: pushで動かしていたらエラーを取りこぼしてマージしてしまった話'
tags:
  - GitHub
  - CI
  - pullrequest
  - GitHubActions
private: false
updated_at: '2022-04-19T12:17:04+09:00'
id: 9599facddcba7b912358
organization_url_name: null
slide: false
ignorePublish: false
---
GitHubを利用して開発する際、プルリクエストでCIを利用して様々なチェックを走らせることがあると思います。
私もGitHub Actionsを使ってプルリクにPushするたびに様々なチェックを走らせていたのですが、タイトルの通りエラーを取りこぼしてマージしてしまうことがありました。

# 状況再現

例えば下記の場合、fuga ciとhoge ciがコケているのでこのプルリクの修正で何か問題が発生したことを検知できます。

![スクリーンショット 2021-09-30 10.05.57.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/83424/b0fbf869-2d5f-b8ca-42a3-3f5488395a00.png)


説明のためかなり簡素化していますが、上記のプルリクでは下記のコードとそれをテストするGitHub Actionsを定義しています。

```bash:hoge/main.sh
#!/bin/bash

exit 1
```

```bash:fuga/main.sh
#!/bin/bash

exit 1
```

```yaml:.github/workflows/hoge.yml
name: hoge ci

on:
  push:
    paths:
      - 'hoge/**'

jobs:
  hoge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: run hoge
        run: hoge/main.sh
```

```yaml:.github/workflows/fuga.yml
name: fuga ci

on:
  push:
    paths:
      - 'fuga/**'

jobs:
  fuga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: run fuga
        run: fuga/main.sh
```

hoge ciはチェック内容が`hoge/**`のファイルに依存しているので、hoge配下のファイルが変更された時だけ実行します。
fuga ciも同様の理由でfuga配下のファイルが変更された時だけ実行します。

今回、hogeもfugaも不具合が埋め込まれたことを表現するためにexit 1としています。そのためCIがエラーになっています。

不具合(exit 1)を修正します。
今回はexit 0に直すだけなので両方一気に直せば良いですが、通常開発の場合、まずはhgoeだけ直すなど1つずつ修正していくことが多いと思います。
今回は最初にhogeだけ直してみます。
hoge/main.shが正常終了するように下記のように`exit 0`に修正してpushします。

```bash:hoge/main.sh
#!/bin/bash

exit 0
```

pushした後、プルリクを確認してみると下記のようになりました。
**「All checks have passed」**
hoge/main.shしか修正しておらず、fuga/main.shの不具合は残ったままにもかかわらずCIが通ってしまいました。

![allcheckshavepassed.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/83424/3da40d1c-75c9-74a7-77a0-b2ff2f7d1a40.png)

よく見ると、「All checks have passed」の下のchecksにfuga ciが含まれていません。
プルリクのマージボタンの箇所に表示されるChecksの判定は最後に動作したChecksの結果が反映されます。
最後のPushではhoge/main.shしか修正していないため、hoge ciしか動作せず、動作したテストは全て正常終了したためCIがパスしたようです。

fuga/main.shに不具合が残ったままですが、このプルリクを見るとCIはパスしているように見えるのでマージしてしまいそうですよね。
冒頭で記載したエラーを取りこぼしたのはこの状況です。エラーがあることに気づかずマージしてしまい、mainブランチに不具合が混入してしまいました。

では、どのようにすればこの状況を避けられるのでしょうか？

# 解決策

タイトルに「on: pushで動かしていたらエラーを取りこぼした話」と書いた通り、`on: push`の挙動に問題があります。

`on: push`を使うと、Pushに含まれるコードをもとに該当するCIが実行されます。
先程の2回目のPushはhoge/main.shのみしか含まれていなかったため、hoge ciのみ実行されました。
この挙動によりfuga ciが実行されずに不具合を見逃してしまいました。

これを避けるためには`on: pull_request`を使用すればよいです。

Github Actionsのonをpull_requestに変更して同様の作業を行います。

```diff:.github/workflows/hoge.yml
name: hoge ci

on:
-  push:
+  pull_request:
    paths:
      - 'hoge/**'
```

```diff:.github/workflows/fuga.yml
name: fuga ci

on:
-  push:
+  pull_request:
    paths:
      - 'fuga/**'
```

実行結果は下記の通り。
![スクリーンショット 2021-09-30 10.52.56.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/83424/c04ab963-eb22-2e18-253f-293ac2686fc3.png)

先ほどと異なり、hogeだけ修正したPushでもfuga ciも動作しています。
`on: pull_request`はpushと異なりpull_requestに含まれるコードをもとに該当するCIが実行されます。
そのため、最後のPushにfuga/main.shが含まれていなくても、プルリク全体で見ると含まれているためfuga ciも実行されます。

これであればhoge ciがコケていることが一目瞭然なので誤ってマージしてしまうこともありません。

# まとめ

上記の挙動より、プルリクエストのCIとして使う場合は`on: pull_request`を使った方が良さそうです。
過去に私が書いた記事はon: pushになっているものが多いので修正しないとな・・・
